_host_hash: "{{ vault_seed + (lookup('ansible.builtin.file', '/etc/hostname') if inventory_hostname == 'localhost' else inventory_hostname) | hash('sha3_512') }}"
ansible_user: "ansible{{ _host_hash | hash('md5') | truncate(4, true, '') | int(base=16) }}"
ansible_become_password: "{{ _host_hash | truncate(128, true, '') }}"
