---
- name: Convert packages to list if its a string
  ansible.builtin.set_fact:
    packages: "{{ [packages] | flatten }}"
  when: packages is string
  no_log: true
- name: Find install tasks files for {{ packages | join(', ') }}
  ansible.builtin.script:
    cmd: >
      install.sh
      package={{ item }}
      distribution_major_version={{ ansible_facts['distribution_major_version'] }}
      distribution_release={{ ansible_facts['distribution_release'] }}
      distribution_version={{ ansible_facts['distribution_version'] }}
      distribution={{ ansible_facts['distribution'] }}
      os_family={{ ansible_facts['os_family'] }}
      pkg_mgr={{ ansible_facts['pkg_mgr'] }}
    chdir: "{{ role_path }}/tasks"
  register: script_output
  changed_when: false
  loop: "{{ packages }}"

- name: Include found install tasks files
  ansible.builtin.include_tasks:
    file: "{{ item.stdout_lines[0] }}"
  loop: "{{ script_output.results }}"
